[package]
name = "bevy-tutorial"
version = "0.1.0"
description = "sample"
authors = ["usagrada <usagrada.kind@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
